### ISSUE TITLE
WhatsApp works with Google Chrome 60+, update Google Chrome

### ISSUE THREAD

**Issue by Fidelity88** [amanharwara/altus#178]
Can't use Altus 4.5.3 anymore since this morning.

A message pops up to update to the latest Google Chrome version. I've tried updating my local Google Chrome but I don't think it's connected. Force reloading doesn't fix the problem either.

**Comment by amanharwara** [comment]
Please use 4.5.2 for the time being. I'm aware of what's causing this, but can't roll out a fix yet

**Comment by amanharwara** [comment]
Could you test this? https://github.com/amanharwara/altus/releases/tag/4.5.4

**Comment by Fidelity88** [comment]
Unfortunately it doesn't work. The problem with the "update to the latest Google Chrome" does go away, but now the issue is that the fix  in issue 159 https://github.com/amanharwara/altus/issues/159 seems reverted.

So I see "Connecting to WhatsApp" message again after using 4.5.4

**Comment by amanharwara** [comment]
The trouble I'm having with this is that the fix for the "Update Chrome" thing is what causes the Multi-device beta to stop working, and vice-versa.

**Comment by Fidelity88** [comment]
Ok, well I just checked. This is indeed working when I disable the Multi-device beta again. So for now, this works for me :) 
Thanks for all your support and effort! If you need me to test a new version again with the beta enabled, let me know!

**Comment by amanharwara** [comment]
Right now, to fix the "Update Chrome" error, Altus unregisters the service workers, and clears the WebSQL db and the IndexedDB attached to WhatsApp. Admittedly, I'm not sure if clearing all of that is required. If somebody can isolate what we need to clear/unregister to fix the "Update Chrome" error, then it might be possible to only remove that, and keep what's necessary for the Multi-device beta to work.

**Comment by RayneShall** [comment]
The 'Update Chrome' message pops up again for me in 4.5.4 after rebooting the pc. Closing the tab and creating a new one fixes it, but that means recreating the tab and settings on every boot...

**Comment by amanharwara** [comment]
> The 'Update Chrome' message pops up again for me in 4.5.4 after rebooting the pc. Closing the tab and creating a new one fixes it, but that means recreating the tab and settings on every boot...

In that case right now, you'll need to downgrade to v4.5.2.

**Comment by Fidelity88** [comment]
@RayneShall I had the same problem, but after clicking 'Clear cache' (under settings) and then 'Force reload' fixed the problem. It does however seem to be a temp fix. After a couple of restarts, the 'Update Chrome' message does seem to pop up again. But simply follow above steps again to fix it again!

**Comment by RayneShall** [comment]
Clear Cache + Force Reload definitely fixes it temporarily. That's a good enough workaround for now. 

I'll keep 4.5.2 around just in case.

**Comment by amanharwara** [comment]
> but after clicking 'Clear cache' (under settings) and then 'Force reload' fixed the problem.

@Fidelity88 After you did this, was the multi-device beta working for you?

**Comment by Fidelity88** [comment]
> > but after clicking 'Clear cache' (under settings) and then 'Force reload' fixed the problem.
> 
> @Fidelity88 After you did this, was the multi-device beta working for you?

Haven't tried that yet. I was referring to the use of 'multi-device beta' as disabled.

But I've tested this now. The result is very weird... When I clear the cache and force reload. The notice as stated in my first comment (update to the latest Google Chrome version) is gone! So it seemed to work, but... WhatsApp doesn't load in. It stays on the 'Connecting to WhatsApp' screen for a long time. Then after maybe 1 or 2 minutes have passed, it shows an error 'Connecting to WhatsApp, make sure your computer has an active internet connection'

![Screenshot 2021-12-10 at 14 24 40](https://user-images.githubusercontent.com/2750761/145580878-b104f774-1e02-4474-b158-f67cd34e29b2.png)


So yes, the beta is working. But unusable.

**Comment by amanharwara** [comment]
Forgot to mention it here, but the [latest version](https://github.com/amanharwara/altus/releases/tag/4.7.1) should fix this.

**Comment by Pixopax** [comment]
Yep, 4.7.4 here also. Now way to run it this way.
![image](https://user-images.githubusercontent.com/17147865/191426891-22d3f9ed-9477-405d-882b-cc92510811c0.png)

**Comment by Pixopax** [comment]
Moved back to 4.7.1, than it works, but only with a single account.

**Comment by amanharwara** [comment]
Should be fixed in [v4.8.0](https://github.com/amanharwara/altus/releases/tag/4.8.0) (Can take a few seconds to auto-reload)

**Comment by Tokarak** [comment]
In 4.8.0 the message still appears, but cmd+r to reload fixes it. I can confirm that it appears after "suspend to ram". Any cleaner way to stop the message popping up completely?

**Comment by Tokarak** [comment]
I found the following resources on a similar project discussing the same problem: nativefier/nativefier#1112. They did come up with a solution similar to the one being used now.

But there seems to be a more robust way of fixing this. nativefier/nativefier#1312 is the suggested solution and nativefier/nativefier#1316 is the PR. Implementing nativefier/nativefier#1316 seems much cleaner than the current patchwork.

**Comment by amanharwara** [comment]
> I found the following resources on a similar project discussing the same problem: [nativefier/nativefier#1112](https://github.com/nativefier/nativefier/issues/1112). They did come up with a solution similar to the one being used now.
> 
> But there seems to be a more robust way of fixing this. [nativefier/nativefier#1312](https://github.com/nativefier/nativefier/issues/1312) is the suggested solution and [nativefier/nativefier#1316](https://github.com/nativefier/nativefier/pull/1316) is the PR. Implementing [nativefier/nativefier#1316](https://github.com/nativefier/nativefier/pull/1316) seems much cleaner than the current patchwork.

Very interesting. Implemented this and it looks good on my side. Will put out a release with this soon.

Thank you very much!

**Comment by vMawk** [comment]
Hi 👋

I’ve opened a PR that fixes this by setting a newer Chrome user agent (Chrome 120) in the webview.
https://github.com/amanharwara/altus/pull/384
